### ISSUE TITLE
Broken Transmission settings feature and destination directory option when adding torrent

### ISSUE THREAD

**Issue by xF4m3** [theroyalstudent/layered#26]
1. I would like to use [] those in some download folder names, i can do this via the config file of transmission without any issues, but doing it over the webpage creates very wierd folder names with lots of numbers and % and all that crap. It would be really nice if you could make that possible. 

2. On that note, it would be very convinient if you could set a downlaod directory like you can atm (with above issue fixed) and additionally be able to change the directory when you add a torrent, as an optional line, if you do not supply a location seperately and leave it blank, it should fall back to the default location set in the options menu.

**Comment by runbiscuit** [comment]
I'm pretty unclear about what you're trying to say in the first feature, mind explaining further? :)

The second feature that you should be workable, let me try to throw that in later :)

I'm currently working on a proper code cleanup, as it doesn't perform well with my seedbox, which has 260+ torrents.

**Comment by xF4m3** [comment]
Yeah i have 290+ torrents in mine, code cleanup would be nice, i cleared them once already because it took so long to load. 
With the first issue i mean that I would like to make folder names like this "/mnt/data/downloadname [1080p]" so basically the special Characters [] are not supported atm. 
For example, just put in the options under download-dir "test-[BD]" (just refresh the page and look into the options again and you will see what i mean) that turned into "test-%5BBD%5D". I hope this makes it clear.
 If i do the same directly via the config file for transmission it works fine, i just can not edit the options over the webpage anymore, since it will try to override it with this wierd combination of charakters insead of [BD].

**Comment by runbiscuit** [comment]
I've tested special symbols like [] and they don't seem to work as you've said - this is an issue with Transmission itself, instead of this web interface. I've seen it POSTing the data the way it should in Inspect Element, so it's a problem with Transmission itself, I suppose.

I will be happy to pull out a stock version of Transmission with the original WebUI and test it, if I have time.

Cheers!

**Comment by xF4m3** [comment]
Well I do not know the specifics how this works since i am pretty bad at programming and stuff, i can barely change the colors of stuff hehe, but you can input it in the config file for transmission, if you insert it using an editor it works fine, also I use another programm to automatically download some Episodes i watch called "Flexget with the addon transmissionrpc" with this i also can set my foldernames with [1080p] since i always lable my folders with the quality, and it looks the best using those [ ] brakets. So i am pretty sure that this is not directly an issue with transmission or the api.

Since most of my downlaods are issued through flexget i do not have a big issue with this, and i usually can set the folder with an editor directly in the config for those rare occasions i manually need to set the downlaodfolder and add torrents. But it definetly would be an appreciated change/fix. 

Best Regards!

**Comment by xF4m3** [comment]
I probably should add that you need to stop the transmission deamon first in order to change the configfile by hand, stop the transmission-deamon, then edit the file for me located in "/var/lib/transmission-daemon/info/settings.json" and then start the deamon again.

**Comment by runbiscuit** [comment]
Hiya, do take a look at the develop branch, I've pushed a new commit that allows you to set download directory when adding torrent!

Also, regarding setting "[]" in torrent names, it really seems to be an issue with Transmission, I would recommend you to use `script-torrent-done-enabled` (set to true) and `script-torrent-done-filename` (set to a script), and for the script, you could write a script that replaces "%5B" with "[" and "%5D" with "]".

As for the configuration file editing, from my memory you only need to stop `transmission-daemon` to change `download-dir`.

Cheers! Do close this if it's the download directory (when adding) works nicely :)

**Comment by xF4m3** [comment]
Hey awesome, yes setting the download directory when addin a torrent seperately works fine.

"As for the configuration file editing, from my memory you only need to stop transmission-daemon to change download-dir." 
Thats exactly what I meant, I meant for the change of the directory, not for other settings.

How do you change the download directory? you also stop the deamon and then insert the new directory name right? If doing that by hand works, why wouldn't it work with the website? Only thing i can imagin is that the method you use for "storing" (i mean storing in a variable or however its done in your code) the new download directory in the config .

http://stackoverflow.com/questions/9966053/what-does-5b-and-5d-in-post-requests-stand-for

According to the answer there, %5B is '[' and %5D is ']' 
This is called percent encoding and is used in encoding special characters in the url parameter values.

So I think that when you store it inside your variable it uses the wrong encoding so that the special characters get. 

If you could tell me in which file and line you process the download directory and save the config, i would try to look into that with a friend of mine and could try to figure out how we can get this working. 
But since i can define the downlaod directory while adding a torrent for me that does not pose a big issue. I dont really change the settings anyway.

And awesome that you could implement the adding thing 
Cheers! :D

Edit: I seem to be unable to edit the config file at all after i updated to the development Branch, does it work for you? if yes, i might have a permission issue on my end, but as far as i can tell, the settings file is owned by the transmission user. Website says it saved it successfully, but after reloading the page and looking at the config option i changed it is back to the old one.

**Comment by runbiscuit** [comment]
I'll look into the encoding thing!

As for the configuration file, only the speed limit mode option seems to work. Will get to cloning the original web interface to test it out.

**Comment by runbiscuit** [comment]
Found the issue (for the configuration file)

![transmissionvslayered](https://cloud.githubusercontent.com/assets/7458463/23587687/cffb3dac-01ec-11e7-8df3-f8e501996cc6.png)

**Comment by runbiscuit** [comment]
I've updated the develop branch with the commit that fixes the settings. Do kindly test it - it works great now, special characters are fixed now too :)

Get back to me soon, cheers!

**Comment by xF4m3** [comment]
For me the Settings still don't get saved. Which version of transmission do you use? Mine is 2.92. Its "transmission-daemon --version" if you don't know the command. 
When i change the settings and save it, then reload the page and look at the setting again it still didnt change. Also i made sure all my permission are set correctly and transmission-daemon is the owner and group of the settings file. I assume it might be because of the version? Not sure

The special Charakter works great when I specify a directory when addin a torrent Thumbs up for that, thats awesome. 
Thanks for fixing that :D

**Comment by runbiscuit** [comment]
Looks like it's fixed now. Added partial localisation support, unit formats may be wrong or show up as NaN. Working on it.

**Comment by xF4m3** [comment]
Yeah definetly works now, I can save settings (its normal that the config file only gets saved when transmission restarts or shutsdown right, if so then all is good) and I can also use special charakerts inside the settings config :D 

I really appreciate all your effort @theroyalstudent 
Thanks man 

I'm not sure what you mean with 

>  Added partial localisation support, unit formats may be wrong or show up as NaN. 

But for me everything looks fine as far as i can tell , except for one NaN under a specific torrent information it says 1084 * NaN for the Pieces. 

So i guess this can be closed now

Great Work!!!
Cheers! Have an awesome day
